class STRINGS:
    TRAIN_PATH = ""
    VALIDATION_PATH = ""
    TRAIN_ANNOTATION_PATH = ""
    VALIDATION_ANNOTATION_PATH = ""
    def string(self, TRAIN_PATH, VALIDATION_PATH, TRAIN_ANNOTATION_PATH,VALIDATION_ANNOTATION_PATH):
        self.TRAIN_PATH = TRAIN_PATH
        self.VALIDATION_PATH = VALIDATION_ANNOTATION_PATH
        self.TRAIN_ANNOTATION_PATH = TRAIN_ANNOTATION_PATH
        self.VALIDATION_ANNOTATION_PATH = VALIDATION_ANNOTATION_PATH
        
